<?php

declare(strict_types=1);

namespace App\Domain\Strava\Gear;

final readonly class DistanceOverTimePerGearChartBuilder
{
    private function __construct()
    {
    }

    public static function fromGear(): self
    {
        return new self();
    }

    /**
     * @return array<mixed>
     */
    public function build(): array
    {
        return [
            'animation' => true,
            'grid' => [
                'left' => '3%',
                'right' => '4%',
                'bottom' => '3%',
                'containLabel' => true,
            ],
            'tooltip' => [
                'trigger' => 'axis',
                'axisPointer' => [
                    'type' => 'shadow',
                ],
            ],
            'legend' => [
                'selected' => [
                    'MTB' => false,
                ],
            ],
            'toolbox' => [
                'feature' => [
                    'dataZoom' => [
                        'yAxisIndex' => 'none',
                    ],
                    'restore' => [
                    ],
                ],
            ],
            'xAxis' => [
                [
                    'type' => 'category',
                    'axisTick' => [
                        'show' => false,
                    ],
                    'data' => [
                        '2012',
                        '2013',
                        '2014',
                        '2015',
                        '2016',
                        '2012',
                        '2013',
                        '2014',
                        '2015',
                        '2016',
                        '2012',
                        '2013',
                        '2014',
                        '2015',
                        '2016',
                        '2012',
                        '2013',
                        '2014',
                        '2015',
                        '2016',
                        '2012',
                        '2013',
                        '2014',
                        '2015',
                        '2016',
                        '2012',
                        '2013',
                        '2014',
                        '2015',
                        '2016',
                        '2012',
                        '2013',
                        '2014',
                        '2015',
                        '2016',
                        '2012',
                        '2013',
                        '2014',
                        '2015',
                        '2016',
                        '2012',
                        '2013',
                        '2014',
                        '2015',
                        '2016',
                    ],
                ],
            ],
            'yAxis' => [
                [
                    'type' => 'value',
                ],
            ],
            'dataZoom' => [
                [
                    'type' => 'inside',
                    'start' => 90,
                    'end' => 100,
                    'minSpan' => 10,
                    'maxSpan' => 10,
                    'brushSelect' => false,
                    'zoomLock' => true,
                ],
                [
                ],
            ],
            'series' => [
                [
                    'name' => 'Zwift Hub',
                    'type' => 'bar',
                    'barGap' => 0,
                    'emphasis' => [
                        'focus' => 'series',
                    ],
                    'label' => [
                        'show' => true,
                        'position' => 'insideBottom',
                        'verticalAlign' => 'middle',
                        'align' => 'left',
                        'rotate' => 90,
                        'distance' => 15,
                        'formatter' => '{distance|{c} km} - {a}',
                        'rich' => [
                            'distance' => [
                                'fontSize' => 14,
                            ],
                        ],
                    ],
                    'data' => [
                        320,
                        332,
                        301,
                        334,
                        390,
                        320,
                        332,
                        301,
                        334,
                        390,
                        320,
                        332,
                        301,
                        334,
                        390,
                        320,
                        332,
                        301,
                        334,
                        390,
                        320,
                        332,
                        301,
                        334,
                        390,
                        320,
                        332,
                        301,
                        334,
                        390,
                        320,
                        332,
                        301,
                        334,
                        390,
                        320,
                        332,
                        301,
                        334,
                        390,
                        320,
                        332,
                        301,
                        334,
                        390,
                    ],
                ],
                [
                    'name' => 'Stadsfiets',
                    'type' => 'bar',
                    'barGap' => 0,
                    'emphasis' => [
                        'focus' => 'series',
                    ],
                    'label' => [
                        'show' => true,
                        'position' => 'insideBottom',
                        'verticalAlign' => 'middle',
                        'align' => 'left',
                        'rotate' => 90,
                        'distance' => 15,
                        'formatter' => '{distance|{c} km} - {a}',
                        'rich' => [
                            'distance' => [
                                'fontSize' => 14,
                            ],
                        ],
                    ],
                    'data' => [
                        220,
                        182,
                        191,
                        234,
                        290,
                        220,
                        182,
                        191,
                        234,
                        290,
                        220,
                        182,
                        191,
                        234,
                        290,
                        220,
                        182,
                        191,
                        234,
                        290,
                        220,
                        182,
                        191,
                        234,
                        290,
                        220,
                        182,
                        191,
                        234,
                        290,
                        220,
                        182,
                        191,
                        234,
                        290,
                        220,
                        182,
                        191,
                        234,
                        290,
                        220,
                        182,
                        191,
                        234,
                        290,
                    ],
                ],
                [
                    'name' => 'MTB',
                    'type' => 'bar',
                    'barGap' => 0,
                    'emphasis' => [
                        'focus' => 'series',
                    ],
                    'label' => [
                        'show' => true,
                        'position' => 'insideBottom',
                        'verticalAlign' => 'middle',
                        'align' => 'left',
                        'rotate' => 90,
                        'distance' => 15,
                        'formatter' => '{distance|{c} km} - {a}',
                        'rich' => [
                            'distance' => [
                                'fontSize' => 14,
                            ],
                        ],
                    ],
                    'data' => [
                        150,
                        232,
                        201,
                        154,
                        190,
                        150,
                        232,
                        201,
                        154,
                        190,
                        150,
                        232,
                        201,
                        154,
                        190,
                        150,
                        232,
                        201,
                        154,
                        190,
                        150,
                        232,
                        201,
                        154,
                        190,
                        150,
                        232,
                        201,
                        154,
                        190,
                        150,
                        232,
                        201,
                        154,
                        190,
                        150,
                        232,
                        201,
                        154,
                        190,
                        150,
                        232,
                        201,
                        154,
                        190,
                    ],
                ],
            ],
        ];
    }
}
